name: vpython sandbox
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - numpy==1.26.4
    #- jupyterlab==3.6.4
    #- notebook==6.4.12
    #- vpython==7.6.4
    #- jupyterlab-vpython==3.1.4
    - jupyterlab==3.1.0
    - notebook==6.4.0
    - vpython==7.6.2
    - jupyterlab-vpython==3.1.1

